
services:

  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    networks:
      - ckannet
      - solrnet
      - redisnet
    env_file:
      - .env
    depends_on:
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ckan_storage:/var/lib/ckan
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.12/site-packages
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://${LOCALHOST}:${CKAN_PORT_HOST}/api/action/status_show"]
      interval: 60s
      timeout: 10s
      retries: 3

  solr:
    networks:
      - solrnet
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://${LOCALHOST}:${SOLR_PORT}/solr/"]

  redis:
    image: redis:${REDIS_VERSION}
    networks:
      - redisnet
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:${NGINX_PM_VERSION}
    networks:
      - webnet
      - solrnet
      - redisnet
      - ckannet
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      ckan:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 3s
    ports:
      - "${NGINX_PM_HTTPPORT}:${NGINX_PM_HTTPPORT}"
      - "${NGINX_PM_HTTPSPORT}:${NGINX_PM_HTTPSPORT}"
      - "${NGINX_PM_ADMINPORT}:${NGINX_PM_ADMINPORT}"
    volumes:
      - nginx_pm_data:/data
      - ssl_data:/etc/letsencrypt

networks:
  webnet:
  ckannet:
  solrnet:
    internal: true
  redisnet:
    internal: true

volumes:
  ckan_storage:
  solr_data:
  pip_cache:
  site_packages:
  nginx_pm_data:
  ssl_data:
