name: Build CKAN Docker 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1
    -  name: CKAN build
       uses: docker/build-push-action@v2
       with:
          context: ./ckan
          file: ./ckan/Dockerfile
          push: false
          tags: kowhai/ckan-docker-ckan:test-build-only
      